parameters:
#    parametro: 'valor del parametro'

services:
#    stg_theme.example:
#        class: STG\ThemeBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    stgtheme.twig_extension:
        class: STG\ThemeBundle\Twig\STGThemeExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }