parameters:
    title: 'Titulo de la aplicación'
    entity: 'Organismo que desarrolla'

services:
#    stg_theme.example:
#        class: STG\ThemeBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
