parameters:
#    parametro: 'valor del parametro'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    stgtheme.twig_extension:
        class: STG\ThemeBundle\Twig\STGThemeExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }

    STG\ThemeBundle\Controller\DefaultController:
        arguments: ['@parameter_bag']
