parameters:
#    parametro: 'valor del parametro'

services:
#    stg_theme.example:
#        class: STG\ThemeBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

stg.deim.themes.aplicativo.twig.global_data_extension:
        class: STG\ThemeBundle\Twig\GlobalDataExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }